from django.shortcuts import render

# Create your views here.
from rest_framework import permissions, status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from django.shortcuts import get_object_or_404
from rest_framework import permissions, status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from .models import Article
from .serializers import PostArticleSerializer, ArticleSerializer

# Create a new blog post with optional featured image and slug
@api_view(['POST'])
@permission_classes([permissions.IsAuthenticated])
def blog_create(request):
    if request.method == 'POST':
        serializer = PostArticleSerializer(data=request.data)
        if serializer.is_valid():
            # Save the post, slug is automatically generated by the save method
            serializer.save(author=request.user)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

# Update a specific blog post with optional featured image and slug
@api_view(['PUT'])
@permission_classes([permissions.IsAuthenticated])
def blog_update2(request, pk):
    try:
        post = Article.objects.get(pk=pk)
    except Article.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if post.author != request.user:
        return Response(status=status.HTTP_403_FORBIDDEN)

    serializer = ArticleSerializer(post, data=request.data)
    if serializer.is_valid():
        # Save the post, slug is automatically generated or updated
        serializer.save()
        return Response(serializer.data)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

# Get a specific blog post by slug
@api_view(['GET'])
def blog_detail(request, slug):
    post = get_object_or_404(Article, slug=slug)
    serializer = ArticleSerializer(post)
    return Response(serializer.data)

# Update a specific blog post by slug
@api_view(['PUT'])
@permission_classes([permissions.IsAuthenticated])
def blog_update(request, slug):
    post = get_object_or_404(Article, slug=slug)

    if post.author != request.user:
        return Response(status=status.HTTP_403_FORBIDDEN)

    serializer = ArticleSerializer(post, data=request.data)
    if serializer.is_valid():
        serializer.save()
        return Response(serializer.data)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

# Delete a specific blog post by slug
@api_view(['DELETE'])
@permission_classes([permissions.IsAuthenticated])
def blog_delete(request, slug):
    post = get_object_or_404(Article, slug=slug)

    if post.author != request.user:
        return Response(status=status.HTTP_403_FORBIDDEN)

    post.delete()
    return Response(status=status.HTTP_204_NO_CONTENT)

@api_view(['GET'])
def blog_list(request):
    posts = Article.objects.all()
    serializer = ArticleSerializer(posts, many=True)
    return Response(serializer.data)