# Generated by Django 3.2.16 on 2022-11-09 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investor', '0002_investor_serialkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expectations',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='investmentsize',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='period',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='created_by',
        ),
        migrations.CreateModel(
            name='InitialInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_interest_set', to='investor.interest')),
                ('investmentsize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_size_set', to='investor.investmentsize')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_authentication_set', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_period_set', to='investor.period')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_authentication_set', to='investor.risk')),
            ],
        ),
    ]
