# Generated by Django 2.2.5 on 2022-10-27 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrals',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners_authentication_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referrals',
            name='referred',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_authentication_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
