# Generated by Django 3.2.16 on 2022-11-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20221108_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedln',
            field=models.TextField(null=True),
        ),
    ]
