# Generated by Django 3.2.16 on 2022-11-10 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_linkedln'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrals',
            name='referred',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='referral_authentication_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
