# Generated by Django 3.2.16 on 2023-02-11 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_sponsor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
