# Generated by Django 3.2.16 on 2023-02-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_profile_nin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_investor',
            field=models.BooleanField(default=False),
        ),
    ]
