# Generated by Django 3.2.16 on 2023-03-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_user_is_investor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_investor',
            new_name='is_issuer',
        ),
    ]
