# Generated by Django 3.2.16 on 2023-03-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_profile_is_sponsor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_sponsor',
            new_name='is_investor',
        ),
    ]
