# Generated by Django 3.1.1 on 2023-06-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_rename_is_sponsor_profile_is_investor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nin',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
