# Generated by Django 5.0.4 on 2024-09-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_auto_20230628_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_investor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='next_of_kin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_issuer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_vendor',
        ),
    ]
