# Generated by Django 2.2.5 on 2022-11-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investors',
            name='serialkey',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
