# Generated by Django 2.2.5 on 2022-11-01 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_investors_serialkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_investment_set', to='investment.Investment'),
        ),
    ]
