# Generated by Django 2.2.5 on 2022-11-04 16:11

from django.db import migrations, models
import investment.models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_auto_20221101_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery',
            field=models.ImageField(default='post/default.jpg', upload_to=investment.models.upload_to, verbose_name='Gallery'),
        ),
    ]
