# Generated by Django 2.2.5 on 2022-11-04 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_auto_20221104_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='investment.InvestmentRoom'),
        ),
    ]
