# Generated by Django 2.2.5 on 2022-11-04 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0005_auto_20221104_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='investment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment_gallery_set', to='investment.Investment'),
        ),
    ]
