# Generated by Django 2.2.5 on 2022-11-05 02:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0007_auto_20221105_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='features',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
