# Generated by Django 2.2.5 on 2022-11-05 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0008_auto_20221105_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_set', to='investment.Investment'),
        ),
    ]
