# Generated by Django 2.2.5 on 2022-11-05 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0009_auto_20221105_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_period', to='investor.Period'),
        ),
    ]
