# Generated by Django 2.2.5 on 2022-11-05 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0010_auto_20221105_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.InvestmentRoom'),
        ),
    ]
