# Generated by Django 2.2.5 on 2022-11-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0011_auto_20221105_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='features',
            field=models.TextField(),
        ),
    ]
