# Generated by Django 3.2.16 on 2022-11-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0013_auto_20221115_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='investors',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=200, null=True),
        ),
    ]
