# Generated by Django 3.2.16 on 2022-11-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0014_auto_20221115_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='investors',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
