# Generated by Django 3.2.16 on 2022-11-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0015_auto_20221116_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='investmentroom',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='features',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='investmentroom',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
