# Generated by Django 3.2.16 on 2022-11-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0016_auto_20221118_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
