# Generated by Django 3.2.16 on 2022-11-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0017_investment_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
