# Generated by Django 3.2.16 on 2022-11-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0018_investment_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='investors',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
