# Generated by Django 3.2.16 on 2022-12-12 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investment', '0020_auto_20221126_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DealType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='investment',
            name='bid_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='offer_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='spot_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='unit_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='video',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='volume',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='investmentroom',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MainRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('description', models.TextField(null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='investment',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_currency', to='investment.currency'),
        ),
        migrations.AddField(
            model_name='investment',
            name='dealtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_dealtype', to='investment.dealtype'),
        ),
        migrations.AddField(
            model_name='investmentroom',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_room', to='investment.mainroom'),
        ),
    ]
