# Generated by Django 3.2.16 on 2022-12-12 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0021_auto_20221212_0527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentroom',
            old_name='main_category',
            new_name='main_room',
        ),
    ]
