# Generated by Django 3.2.16 on 2022-12-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0022_rename_main_category_investmentroom_main_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='bid_price',
        ),
        migrations.AddField(
            model_name='investors',
            name='bid_price',
            field=models.IntegerField(null=True),
        ),
    ]
