# Generated by Django 3.2.16 on 2022-12-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0023_auto_20221212_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
