# Generated by Django 3.2.16 on 2022-12-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0024_auto_20221213_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='maximum_allotment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='milestone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='minimum_allotment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='project_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='project_raise',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='project_value',
            field=models.IntegerField(null=True),
        ),
    ]
