# Generated by Django 3.2.16 on 2022-12-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0026_remove_investment_project_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='offer_period',
            field=models.DateField(null=True),
        ),
    ]
