# Generated by Django 3.2.16 on 2023-01-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0031_investors_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='investors',
            name='investment_type',
            field=models.CharField(choices=[('only returns', 'only returns'), ('off plan', 'off plan'), ('outright purchase', 'outright purchase')], default='only returns', max_length=255),
        ),
    ]
