# Generated by Django 3.2.16 on 2023-02-11 05:52

from django.db import migrations, models
import investment.models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0032_investors_investment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nin', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('dob', models.DateField(null=True)),
                ('address', models.TextField(null=True)),
                ('identity', models.ImageField(default='identity/default.jpg', upload_to=investment.models.identity_to, verbose_name='Identity')),
            ],
        ),
    ]
