# Generated by Django 3.2.16 on 2023-02-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0034_auto_20230214_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
