# Generated by Django 3.2.16 on 2023-02-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0035_sponsor_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='nin',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
