# Generated by Django 3.2.16 on 2023-02-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0036_alter_sponsor_nin'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='construction_status',
            field=models.CharField(choices=[('not started', 'not started'), ('started', 'started'), ('pending', 'pending'), ('in progress', 'in progress'), ('approved', 'approved'), ('completed', 'completed')], default='pending', max_length=255),
        ),
        migrations.AddField(
            model_name='investment',
            name='project_status',
            field=models.CharField(choices=[('not started', 'not started'), ('started', 'started'), ('pending', 'pending'), ('in progress', 'in progress'), ('approved', 'approved'), ('completed', 'completed')], default='not started', max_length=255),
        ),
        migrations.AddField(
            model_name='investment',
            name='title_status',
            field=models.CharField(choices=[('not started', 'not started'), ('started', 'started'), ('pending', 'pending'), ('in progress', 'in progress'), ('approved', 'approved'), ('completed', 'completed')], default='pending', max_length=255),
        ),
    ]
