# Generated by Django 3.2.16 on 2023-02-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0037_auto_20230218_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='investors',
            name='house_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
