# Generated by Django 3.2.16 on 2023-02-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0038_investors_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='roi',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
