# Generated by Django 3.1.1 on 2023-06-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0040_alter_investment_annualized'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='payment',
            field=models.CharField(choices=[('not started', 'not started'), ('partial', 'partial'), ('full', 'full')], default='not started', max_length=255),
        ),
    ]
