# Generated by Django 5.0.4 on 2024-10-06 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0042_auto_20230624_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='owner',
            new_name='user',
        ),
    ]
