# Generated by Django 5.0.4 on 2024-10-06 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0043_rename_owner_investment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='user',
            new_name='owner',
        ),
    ]
