# Generated by Django 3.2.16 on 2023-01-15 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0029_investment_periodic_payment'),
        ('comment', '0003_alter_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='investment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investments_comment', to='investment.investors'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_comment', to='investment.investors'),
        ),
    ]
