# Generated by Django 6.0.3 on 2026-03-31 11:03

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import resources.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("resources", "0001_enable_pg_trgm"),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from title if blank)', max_length=255, unique=True)),
                ('title', models.CharField(help_text='Resource title', max_length=255)),
                ('content', models.TextField(help_text='Rich HTML content')),
                ('excerpt', models.TextField(blank=True, help_text='Short description or summary')),
                ('category', models.CharField(choices=[('article', 'Article'), ('disclosure', 'Disclosure'), ('news', 'News'), ('actions', 'Actions')], default='article', help_text='Resource category', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags (maximum 10)')),
                ('featured_media', models.CharField(blank=True, help_text='URL to featured image or media', max_length=500)),
                ('featured_media_type', models.CharField(blank=True, choices=[('local', 'Local'), ('external', 'External')], default='local', help_text='Type of featured media', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Publication status', max_length=20)),
                ('featured', models.BooleanField(default=False, help_text='Whether this resource is featured')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (if different from resource title)', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description')),
                ('og_image', models.CharField(blank=True, help_text='Open Graph image URL for social sharing', max_length=500)),
                ('author_name', models.CharField(blank=True, help_text='Author display name', max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Publication date')),
                ('link', models.URLField(blank=True, help_text='External link (if resource links to external content)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_user', models.ForeignKey(blank=True, help_text='Author user account (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded file', upload_to=resources.models.media_file_path)),
                ('original_filename', models.CharField(help_text='Original filename before renaming', max_length=255)),
                ('file_type', models.CharField(blank=True, help_text='MIME type or file extension', max_length=50)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(blank=True, help_text='Associated resource (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='resources.resource')),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['category'], name='resources_r_categor_8e2710_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['status'], name='resources_r_status_f37b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['date'], name='resources_r_date_3ca131_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['featured'], name='resources_r_feature_b91302_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['created_at'], name='resources_r_created_215cda_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['updated_at'], name='resources_r_updated_4daa16_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['status', 'category'], name='resources_r_status_366adc_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['status', 'featured'], name='resources_r_status_a5ea1d_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['status', 'category', 'featured'], name='resources_r_status_a6bceb_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='resource_title_gin_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['uploaded_by'], name='resources_m_uploade_9a022b_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['uploaded_at'], name='resources_m_uploade_fa600a_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['resource'], name='resources_m_resourc_341c76_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['file_type'], name='resources_m_file_ty_2f73f0_idx'),
        ),
    ]
